### ISSUE TITLE
rewrite it in Rust.

### ISSUE THREAD

**Issue by aka-deVOID** [HeavySin/PlugProtector#1]
I'm Game if you want to write Plug Protector for Linux

**Comment by HeavySin** [comment]
@aka-deVOID
It has already been rewritten in C++; I wrote it 4 years ago in Python, but that ended up being a real mess.

**Comment by aka-deVOID** [comment]
yes, python is not a good idea, by the way I write Rust so if you need some Rust for something like GUI or Cli tell me

**Comment by HeavySin** [comment]
> yes, python is not a good idea, by the way I write Rust so if you need some Rust for something like TUI or Cli tell me
> @aka-deVOID 

It would be so great if you could write its **Control Panel** Terminal Interface via Rust because it's Terminal-Based!

**Comment by aka-deVOID** [comment]
> > yes, python is not a good idea, by the way I write Rust so if you need some Rust for something like TUI or Cli tell me
> > @aka-deVOID
> 
> It would be so great if you could write its **Control Panel** Terminal Interface via Rust because it's Terminal-Based!

Yeah Why not, if you have Discord send me your ID
